export enum ProjectStates {
  DRAFT = 0,
  REQUEST_MORE_INFO = 1,
  READY_TO_VOTE = 2,
  REJECTED = 3,
  UPCOMING = 4,
  FUNDING_PHASE_1 = 5,
  FUNDING_PHASE_2 = 6,
  FUNDING_PHASE_3 = 7,
  CLOSED = 8,
  FAILED = 9
}
